# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f43935c198c1c6778915a979b7fa6f7887a5fac76fd3465a81d3b3e669078096582a3d946590c9f7a5fbdd222e339a5f3803d7876b7e20208b4b5e23ad1291b

test:
  secret_key_base: 1a9600f19c007b67d1a0f1d8dfe13c3244462771e333cb36e6edcc78dbbf0082b5d2922dd3211b311df286b44ce7e4333ab65c38ab544bb11e8ab4e3e0028c98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
